[build]
  # Base directory
  base = "frontend"
  # Directory with the frontend build output (relative to base)
  publish = "dist"
  # Build command for the frontend only
  command = "npm install && npm run build && cd netlify/functions && npm install"
  # Directory with Netlify Functions for API proxying (relative to base)
  functions = "netlify/functions"

# API proxy redirects - using force=true to ensure the redirects take precedence
[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200
  force = true

[[redirects]]
  from = "/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200
  force = true

[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/test-endpoint"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-proxy/:splat"
  status = 200
  force = true

# Redirects for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200