[build]
  # Directory with the frontend build output
  publish = "frontend/dist"
  # Build command for the frontend
  command = "cd frontend && npm install && npm run build"

# Redirects for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200