[build]
  # Base directory
  base = "frontend"
  # Directory with the frontend build output (relative to base)
  publish = "dist"
  # Build command for the frontend only
  command = "npm install && npm run build && cd netlify/functions && npm install"
  # Directory with Netlify Functions for API proxying (relative to base)
  functions = "netlify/functions"

# API routes for events
[[redirects]]
  from = "/api/events"
  to = "/.netlify/functions/events"
  status = 200
  force = true

[[redirects]]
  from = "/api/events/*"
  to = "/.netlify/functions/events/:splat"
  status = 200
  force = true

# Other API routes handled by api.js
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Auth endpoints
[[redirects]]
  from = "/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200
  force = true

[[redirects]]
  from = "/auth/me"
  to = "/.netlify/functions/auth-me"
  status = 200
  force = true

# Test endpoints
[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/test-endpoint"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-proxy/:splat"
  status = 200
  force = true

# Redirects for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200